"""Reusable inorganic crystal-chemistry calculations and results."""

from .contacts import (
    ComponentPairInterpretation,
    ContactClassification,
    CoordinationShell,
    CrystalChemistryResolution,
    EvidenceStatus,
    ResolutionStatus,
    ResolvedContact,
    ResolvedContactOrbit as LegacyResolvedContactOrbit,
    SecondaryEvidence,
    ShellAlternative,
)
from .policy import ShellResolutionPolicy
from .orbit_contacts import (
    ContactInterpretation,
    ContactOrbitResolution,
    ContactOrbitResolver,
    EndpointRole,
    EndpointRoles,
    OrientationMode,
    ResolvedContactOrbit,
)
from .incidence_orbits import ContactIncidenceBuilder, ContactIncidenceOrbit
from .polyhedra import (
    CoordinationPolyhedron,
    CoordinationPolyhedronOrbit,
    FaceSignature,
    PolyhedronBuildResult,
    PolyhedronBuilder,
    PolyhedronVertex,
    canonical_face_signature,
    polyhedron_face_signature,
    unique_hull_edges,
)
from .resolver import CoordinationShellResolver
from .shannon_distance import ShannonDistanceCheck, ShannonDistanceValidator
from .structural_units import (
    StructuralUnit,
    StructuralUnitBuildResult,
    StructuralUnitBuilder,
    StructuralUnitGeometry,
    StructuralUnitGeometryKind,
    StructuralUnitKind,
    StructuralUnitOrbit,
)
from .structural_graph import (
    StructuralConnection,
    StructuralConnectionKind,
    StructuralGraphBuilder,
    StructuralUnitGraph,
)
from .representation import (
    StructuralRepresentation,
    StructuralRepresentationBuilder,
    StructuralSelectionPolicy,
)
from .periodic_connectivity import (
    PeriodicComponent,
    PeriodicConnectivityAnalyzer,
    PeriodicConnectivityResult,
)
from .structural_blocks import (
    StructuralBlock,
    StructuralBlockClassification,
    StructuralBlockFinder,
    StructuralBlockOrbit,
    StructuralBlockResult,
)
from .ring_finder import RingFinder
from .rings import (
    PeriodicUnitRef,
    RingAnalysisResult,
    RingAnalysisStatus,
    RingSearchPolicy,
    StructuralRing,
    StructuralRingOrbit,
    StructuralRingScope,
)

__all__ = [
    "ComponentPairInterpretation",
    "ContactClassification",
    "ContactInterpretation",
    "ContactIncidenceBuilder",
    "ContactIncidenceOrbit",
    "ContactOrbitResolution",
    "ContactOrbitResolver",
    "CoordinationShell",
    "CoordinationShellResolver",
    "CoordinationPolyhedron",
    "CoordinationPolyhedronOrbit",
    "CrystalChemistryResolution",
    "EvidenceStatus",
    "EndpointRole",
    "EndpointRoles",
    "LegacyResolvedContactOrbit",
    "OrientationMode",
    "ResolutionStatus",
    "ResolvedContact",
    "ResolvedContactOrbit",
    "PolyhedronBuildResult",
    "PolyhedronBuilder",
    "PolyhedronVertex",
    "FaceSignature",
    "SecondaryEvidence",
    "ShellAlternative",
    "ShellResolutionPolicy",
    "ShannonDistanceCheck",
    "ShannonDistanceValidator",
    "StructuralUnit",
    "StructuralUnitBuildResult",
    "StructuralUnitBuilder",
    "StructuralUnitGeometry",
    "StructuralUnitGeometryKind",
    "StructuralUnitKind",
    "StructuralUnitOrbit",
    "StructuralConnection",
    "StructuralConnectionKind",
    "StructuralGraphBuilder",
    "StructuralUnitGraph",
    "StructuralRepresentation",
    "StructuralRepresentationBuilder",
    "StructuralSelectionPolicy",
    "PeriodicComponent",
    "PeriodicConnectivityAnalyzer",
    "PeriodicConnectivityResult",
    "StructuralBlock",
    "StructuralBlockClassification",
    "StructuralBlockFinder",
    "StructuralBlockOrbit",
    "StructuralBlockResult",
    "PeriodicUnitRef",
    "RingAnalysisResult",
    "RingAnalysisStatus",
    "RingFinder",
    "RingSearchPolicy",
    "StructuralRing",
    "StructuralRingOrbit",
    "StructuralRingScope",
    "polyhedron_face_signature",
    "canonical_face_signature",
    "unique_hull_edges",
]
